// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import HelloController from "./hello_controller"
import StripeController from "./stripe_controller"
import InvoiceController from "./invoice_controller"

// application.register("hello", HelloController)
application.register("stripe", StripeController)
application.register("invoice", InvoiceController)
